#!/usr/bin/env node
var b = require('bonescript');
var i2c = require('i2c');
var port = '/dev/i2c-2';
var addr = 0x70;
var wire = new i2c(addr, {
    device: '/dev/i2c-2'
});
var MaxX = 16;
var MaxY = 8;
var y = 7;
var x = 0;
var board = [0x80,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	     0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00];

wire.writeByte(0x21, function(err) {
    wire.writeByte(0x81, function(err) {
        wire.writeByte(0xe7, function(err) {
        });
    });
});

function write() {
	board[x] |= 1 << y;
	wire.writeBytes(0x00, board, function(err) {});
};

var buttons = ["P9_11","P9_13","P9_15","P9_17"];
// Pin 11 moves left
// Pin 13 moves up
// Pin 15 moves down
// Pin 17 moves right
// Set pins and interrupts
for (var i = 0; i < buttons.length; i++) {
	b.pinMode(buttons[i],b.INPUT,7,'pulldown');	
};

// For some reason, I have to code each button differently
// Added external pulldown on P9_15
b.attachInterrupt(buttons[0],true,b.RISING,mark);
b.attachInterrupt(buttons[1],true,b.FALLING,mark);
b.attachInterrupt(buttons[2],true,b.FALLING,mark);
b.attachInterrupt(buttons[3],true,b.FALLING,mark);


function mark(i) {
	if (i.pin.key == "P9_17") {
		x = x - 2;
		if (x == -2)
			x = MaxX - 2;
	}
	else if (i.pin.key == "P9_13") {
		y = y - 1;
		if (y == -1)
			y = MaxY - 1;
	}
	else if (i.pin.key == "P9_15") {
		y = y + 1;
		if (y == MaxY)
			y = 0;
	}
	else if (i.pin.key == "P9_11") {
		x = x + 2;
		if (x == MaxX) x = 0;
	}
	write();
};
